/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E13_Table;

import E13_Table.dto.Cliente;
import java.awt.Frame;
import java.util.Date;
import javax.swing.JComboBox;

/**
 *
 * @author DAM2Alu17
 */
public class JDialogAlta extends javax.swing.JFrame {

    /**
     * Creates new form JDialogAlta
     */
    JFrameTable jFramePadre;
    public JDialogAlta(java.awt.Frame parent , boolean modal) {
     //   super(parent,modal);
        initComponents();
        jFramePadre = (JFrameTable)parent; 
                }

    JDialogAlta(JFrameTable aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        JLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        JLabelProvincia = new javax.swing.JLabel();
        Huesca = new javax.swing.JComboBox<>();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelFechaAlta = new javax.swing.JLabel();
        jSpinnerFechaAlta = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButtonAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALTA CLIENTES");

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 10, 8));

        jLabelNombre.setBackground(new java.awt.Color(51, 51, 51));
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setText("Nombre");
        jPanel1.add(jLabelNombre);

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombre.setEnabled(false);
        jPanel1.add(jTextFieldNombre);

        JLabelApellido.setBackground(new java.awt.Color(51, 51, 51));
        JLabelApellido.setForeground(new java.awt.Color(0, 0, 0));
        JLabelApellido.setText("Apellido");
        jPanel1.add(JLabelApellido);

        jTextFieldApellido.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldApellido.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldApellido.setEnabled(false);
        jPanel1.add(jTextFieldApellido);

        JLabelProvincia.setBackground(new java.awt.Color(51, 51, 51));
        JLabelProvincia.setForeground(new java.awt.Color(0, 0, 0));
        JLabelProvincia.setText("Provincia");
        jPanel1.add(JLabelProvincia);

        Huesca.setBackground(new java.awt.Color(255, 255, 255));
        Huesca.setForeground(new java.awt.Color(0, 0, 0));
        Huesca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huesca", "Zaragoza", "Teruel", "Madrid", " " }));
        jPanel1.add(Huesca);

        jLabelMail.setBackground(new java.awt.Color(51, 51, 51));
        jLabelMail.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMail.setText("Mail");
        jPanel1.add(jLabelMail);

        jTextFieldMail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMail.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldMail.setEnabled(false);
        jPanel1.add(jTextFieldMail);

        jLabelEdad.setBackground(new java.awt.Color(51, 51, 51));
        jLabelEdad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEdad.setText("Edad");
        jPanel1.add(jLabelEdad);

        jTextFieldEdad.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEdad.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldEdad.setEnabled(false);
        jPanel1.add(jTextFieldEdad);

        jLabelFechaAlta.setBackground(new java.awt.Color(51, 51, 51));
        jLabelFechaAlta.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFechaAlta.setText("Fecha Alta");
        jPanel1.add(jLabelFechaAlta);

        jSpinnerFechaAlta.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaAlta.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaAlta, "dd/MM/yy,hh/mm"));
        jPanel1.add(jSpinnerFechaAlta);
        jPanel1.add(jLabel2);

        jButtonAlta.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAlta.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAlta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // TODO add your handling code here:
     //   JDialogAlta jDialogAlta = new JDialogAlta(this,true);
     //   jDialogAlta.setVisible(true);
   
   //  Cliente nuevo = new Cliente(jTextFieldNombre.getText(),jTextFieldApellido.getText(),(String)JComboBox.getSelectedItem(),jTextFieldMail.getText(),Integer.valueOf(jTextFieldEdad.getText()),(Date)jSpinnerFechaAlta.getValue());
     //   System.out.println("Cliente "+ nuevo.devuelveFila());
    }//GEN-LAST:event_jButtonAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Huesca;
    private javax.swing.JLabel JLabelApellido;
    private javax.swing.JLabel JLabelProvincia;
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFechaAlta;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFechaAlta;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
