/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contenedor;

import javax.swing.JButton;

/**
 *
 * @author DAM2Alu17
 */
public class JFrameCardLayoutPremium extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCardLayout
     */
    java.awt.CardLayout cardManager; 
    
    public JFrameCardLayoutPremium() {
        initComponents();
        cardManager=new java.awt.CardLayout();
        jPanelPadre.setLayout(cardManager);
        jPanelPadre.add(jPanelClientes,"jPanelClientes");
        jPanelPadre.add(jPanelVehículo,"jPanelVehículo");

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPadre = new javax.swing.JPanel();
        jPanelVehículo = new javax.swing.JPanel();
        jLabelVehículo = new javax.swing.JLabel();
        jPanelClientes = new javax.swing.JPanel();
        jLabelClientes = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        jButtonDelante = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jButtonVehículo = new javax.swing.JButton();
        jButtonSucesor = new javax.swing.JButton();
        jButtonDetras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Vehículos y Clientes");

        jPanelPadre.setBackground(new java.awt.Color(204, 255, 255));
        jPanelPadre.setLayout(new java.awt.CardLayout());

        jPanelVehículo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelVehículo.setBackground(new java.awt.Color(51, 51, 51));
        jLabelVehículo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelVehículo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelVehículo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVehículo.setText("Vehículo");
        jLabelVehículo.setMaximumSize(new java.awt.Dimension(82, 36));
        jLabelVehículo.setMinimumSize(new java.awt.Dimension(82, 36));

        javax.swing.GroupLayout jPanelVehículoLayout = new javax.swing.GroupLayout(jPanelVehículo);
        jPanelVehículo.setLayout(jPanelVehículoLayout);
        jPanelVehículoLayout.setHorizontalGroup(
            jPanelVehículoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehículoLayout.createSequentialGroup()
                .addComponent(jLabelVehículo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jPanelVehículoLayout.setVerticalGroup(
            jPanelVehículoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehículoLayout.createSequentialGroup()
                .addComponent(jLabelVehículo, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jPanelPadre.add(jPanelVehículo, "card2");

        jPanelClientes.setBackground(new java.awt.Color(255, 255, 255));

        jLabelClientes.setBackground(new java.awt.Color(51, 51, 51));
        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(0, 0, 0));
        jLabelClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes.setText("Clientes");
        jLabelClientes.setMaximumSize(new java.awt.Dimension(82, 36));
        jLabelClientes.setMinimumSize(new java.awt.Dimension(82, 36));

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelPadre.add(jPanelClientes, "card3");

        PanelBotones.setBackground(new java.awt.Color(0, 0, 204));

        jButtonDelante.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDelante.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDelante.setText("<<");
        jButtonDelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelanteActionPerformed(evt);
            }
        });
        PanelBotones.add(jButtonDelante);

        jButtonAnterior.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAnterior.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAnterior.setText("<");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        PanelBotones.add(jButtonAnterior);

        jButtonCliente.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCliente.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCliente.setText("Clientes");
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });
        PanelBotones.add(jButtonCliente);

        jButtonVehículo.setBackground(new java.awt.Color(255, 0, 0));
        jButtonVehículo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVehículo.setText("Vehículos");
        jButtonVehículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehículoActionPerformed(evt);
            }
        });
        PanelBotones.add(jButtonVehículo);

        jButtonSucesor.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSucesor.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSucesor.setText(">");
        jButtonSucesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSucesorActionPerformed(evt);
            }
        });
        PanelBotones.add(jButtonSucesor);

        jButtonDetras.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDetras.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDetras.setText(">>");
        jButtonDetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetrasActionPerformed(evt);
            }
        });
        PanelBotones.add(jButtonDetras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 457, Short.MAX_VALUE)
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 47, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        cardManager.show(jPanelPadre, "jPanelClientes"); 
//cardManager.first(jPanelContenedor); //last
//cardManager.previous(jPanelContenedor);//next
        
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonVehículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehículoActionPerformed
     cardManager.show(jPanelPadre, "jPanelVehículo");
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonVehículoActionPerformed

    private void jButtonDelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelanteActionPerformed
        // TODO add your handling code here:
        cardManager.first(jPanelPadre);
    }//GEN-LAST:event_jButtonDelanteActionPerformed

    private void jButtonDetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetrasActionPerformed
       cardManager.last(jPanelPadre);
    }//GEN-LAST:event_jButtonDetrasActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
      cardManager.previous(jPanelPadre);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonSucesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSucesorActionPerformed
       cardManager.next(jPanelPadre);
    }//GEN-LAST:event_jButtonSucesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCardLayoutPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCardLayoutPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCardLayoutPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCardLayoutPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCardLayoutPremium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonDelante;
    private javax.swing.JButton jButtonDetras;
    private javax.swing.JButton jButtonSucesor;
    private javax.swing.JButton jButtonVehículo;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelVehículo;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelPadre;
    private javax.swing.JPanel jPanelVehículo;
    // End of variables declaration//GEN-END:variables
}
