/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E05_Botones;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author DAM2Alu17
 */
public class JFrameBotones extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBotones
     */
    public JFrameBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_01 = new javax.swing.JButton();
        EText_02 = new javax.swing.JLabel();
        jToggleButtonModo = new javax.swing.JToggleButton();
        EText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contador de Clicks");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        btn_01.setText("Pulsa");
        btn_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_01ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_01);

        EText_02.setText("Has pulsado 0 veces");
        jPanel1.add(EText_02);

        jToggleButtonModo.setText("Modo oscuro");
        jToggleButtonModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonModoActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButtonModo);

        EText.setForeground(new java.awt.Color(0, 204, 0));
        EText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EText.setText("CONTADOR DE CLICKS ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EText, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        int contador = 0;
    private void btn_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_01ActionPerformed
       
        // TODO add your handling code here:
        contador++;
        EText_02.setText("Has pulsado "+ contador +" veces");
    }//GEN-LAST:event_btn_01ActionPerformed

    private void jToggleButtonModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonModoActionPerformed
      
        if(jToggleButtonModo.isSelected()){
            this.getContentPane().setBackground(Color.white); //Esto es solo para cambiar el color del panel
            jPanel1.setBackground(Color.white);
        }
        if(!jToggleButtonModo.isSelected()){
              this.getContentPane().setBackground(Color.black);
              jPanel1.setBackground(Color.black);
              EText_02.setForeground(Color.white);
        }
       
    }//GEN-LAST:event_jToggleButtonModoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBotones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EText;
    private javax.swing.JLabel EText_02;
    private javax.swing.JButton btn_01;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButtonModo;
    // End of variables declaration//GEN-END:variables
}
