/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E15_Eventos;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM2Alu17
 */
public class JFramePruebas extends javax.swing.JFrame {

    /**
     * Creates new form JFramePruebas
     */
    public JFramePruebas() {
        initComponents();
        jPanelOculto.setVisible(false);//Para que el panel este no se vea por defecto
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCadena = new javax.swing.JTextField();
        jLabelCadena = new javax.swing.JLabel();
        jTextFieldCopiaCadena = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelContenedor = new javax.swing.JPanel();
        jPanelOculto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonArrastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldCadena.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCadena.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCadena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCadena.setText("Escribe dentro");
        jTextFieldCadena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCadenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCadenaFocusLost(evt);
            }
        });
        jTextFieldCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadenaActionPerformed(evt);
            }
        });
        jTextFieldCadena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCadenaKeyPressed(evt);
            }
        });

        jLabelCadena.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCadena.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextFieldCopiaCadena.setEditable(false);
        jTextFieldCopiaCadena.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCopiaCadena.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCopiaCadena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCopiaCadena.setText("Escribe dentro");
        jTextFieldCopiaCadena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCopiaCadenaFocusLost(evt);
            }
        });
        jTextFieldCopiaCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCopiaCadenaActionPerformed(evt);
            }
        });
        jTextFieldCopiaCadena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCopiaCadenaKeyPressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("jTextField1");
        jTextField1.setDragEnabled(true);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanelContenedor.setBackground(new java.awt.Color(0, 153, 102));
        jPanelContenedor.setForeground(new java.awt.Color(0, 0, 0));
        jPanelContenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelContenedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelContenedorMouseExited(evt);
            }
        });

        jPanelOculto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOculto.setEnabled(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Oculto xD");

        javax.swing.GroupLayout jPanelOcultoLayout = new javax.swing.GroupLayout(jPanelOculto);
        jPanelOculto.setLayout(jPanelOcultoLayout);
        jPanelOcultoLayout.setHorizontalGroup(
            jPanelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOcultoLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );
        jPanelOcultoLayout.setVerticalGroup(
            jPanelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOcultoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PASA EL RATON POR ENCIMA ");

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(jPanelOculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(153, 153, 153))))
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jPanelOculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("COPIA ABAJO CUANDO ESCRIBIMOS");

        jButtonArrastrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonArrastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonArrastrar.setText("Arrastrame");
        jButtonArrastrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButtonArrastrarMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextFieldCopiaCadena, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jTextFieldCadena, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jLabelCadena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonArrastrar)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCopiaCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonArrastrar))
                .addGap(53, 53, 53)
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadenaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Estamos lanzando con un click");
    }//GEN-LAST:event_jTextFieldCadenaActionPerformed

    private void jTextFieldCadenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCadenaFocusLost
        // TODO add your handling code here:
        jLabelCadena.setText(jTextFieldCadena.getText());
       // jTextFieldCadena.setText("Escribe dentro");
       jTextField1.requestFocus();
    }//GEN-LAST:event_jTextFieldCadenaFocusLost

    private void jTextFieldCopiaCadenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCopiaCadenaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCopiaCadenaFocusLost

    private void jTextFieldCopiaCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCopiaCadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCopiaCadenaActionPerformed

    private void jTextFieldCopiaCadenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCopiaCadenaKeyPressed
        // TODO add your handling code here:
        jTextFieldCopiaCadena.setText(jTextFieldCadena.getText());
    }//GEN-LAST:event_jTextFieldCopiaCadenaKeyPressed

    private void jTextFieldCadenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCadenaKeyPressed
        // TODO add your handling code here:
        if(jTextFieldCadena.getText().length()>10){
            jTextFieldCadena.setBackground(Color.blue);
        }else{
            jTextFieldCadena.setBackground(Color.white);
        }
        jTextFieldCadena.setText(jTextFieldCadena.getText());
            
    }//GEN-LAST:event_jTextFieldCadenaKeyPressed

    private void jTextFieldCadenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCadenaFocusGained
        // TODO add your handling code here:
        jTextFieldCadena.setText("");
    }//GEN-LAST:event_jTextFieldCadenaFocusGained

    private void jPanelContenedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelContenedorMouseEntered
        // TODO add your handling code here:
        //Cuando pases el raton por el panel . te lo muestra
        jPanelOculto.setVisible(true);
    }//GEN-LAST:event_jPanelContenedorMouseEntered

    private void jPanelContenedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelContenedorMouseExited
        // TODO add your handling code here:
        //Cuando no pasas el raton por el panel , no se ve el panel oculto 
        jPanelOculto.setVisible(false);
    }//GEN-LAST:event_jPanelContenedorMouseExited

    private void jButtonArrastrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonArrastrarMouseDragged
        // TODO add your handling code here:
        System.out.println("Moviendo a la posicion "+ evt.getPoint());
        jButtonArrastrar.setBounds(evt.getX(),evt.getY(),100,20);
                
            
                
    }//GEN-LAST:event_jButtonArrastrarMouseDragged

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePruebas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArrastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCadena;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelOculto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCadena;
    private javax.swing.JTextField jTextFieldCopiaCadena;
    // End of variables declaration//GEN-END:variables
}
